name: Branch Name Validation

on:
  push:
    branches-ignore:
      - '*'
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch_name
        run: echo "::set-output name=branch_name::${{ github.ref }}"

      - name: Validate branch name
        id: validate_branch_name
        run: |
          branch_name="${{ steps.extract_branch_name.outputs.branch_name }}"
          if [[ ! $branch_name =~ ^[0-9]{4}$ ]]; then
            echo "Invalid branch name: $branch_name"
            exit 1
          else
            echo "Valid branch name: $branch_name"
          fi

      - name: Send error email notification
        if: ${{ job.status != 'success' }}
        env:
          SMTP_SERVER: smtp.example.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: sender@example.com
          EMAIL_TO: recipient@example.com
        run: |
          echo "Subject: Branch Name Validation Error" | tee /tmp/email.txt
          echo "To: $EMAIL_TO" | tee -a /tmp/email.txt
          echo "From: $EMAIL_FROM" | tee -a /tmp/email.txt
          echo "" | tee -a /tmp/email.txt
          echo "Branch name is not valid. Please ensure it consists of four integers." | tee -a /tmp/email.txt
          cat /tmp/email.txt | sendmail -t
