name: Branch Name Check

on:
  push:
    branches-ignore:
      - '*'


jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Get last created branch name
        id: branch_name
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
      
      - name: Validate branch name
        run: |
          branch_name="${{ steps.branch_name.outputs.branch }}"
          if [[ "$branch_name" == sprint/[1-9]+.* || \
                "$branch_name" == feature/D7-[1-9]\{4}.* || \
                "$branch_name" == fix/D7-[1-9]\{4}.* || \
                "$branch_name" == release/[1-9]+.[1-9]+.* ]]; then
            echo "Branch name is valid"
          else
            echo "Branch name is invalid"
            exit 1
          fi
          
      - name: Send error email notification
        if: ${{ job.status != 'success' }}
        run: |
          # Add code to send error email notification here
          echo "Branch name is not valid. Please adhere to coding conventions https://confluencep1.deutsche-boerse.de/display/DD/D7+Git+Workflow?preview=/432375340/432375353/GitWorkflow.pdf."
