name: Branch Name Check

on:
  pull_request:
    types:
      - opened

jobs:
  branch_name_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        run: |
          branch_name=$(git symbolic-ref --short HEAD)
          echo "::set-output name=branch_name::$branch_name"

      - name: Run branch name check
        run: |
          branch_name="${{ steps.branch_name.outputs.branch_name }}"
          cleaned_name=$(echo "$branch_name" | tr -cd '[:digit:]')

          if [ ${#cleaned_name} -eq 4 ]; then
            echo "Branch name is valid."
          else
            echo "Branch name is not valid."
            echo "::set-output name=invalid_branch::true"
          fi

      - name: Send notification to pull request
        if: steps.branch_name_check.outputs.invalid_branch == 'true'
        run: |
          branch_name="${{ steps.branch_name.outputs.branch_name }}"
          github_token="${{ secrets.GITHUB_TOKEN }}"
          comment="The branch name '$branch_name' is not valid. Please ensure the branch name consists of exactly four integers."

          curl -s -X POST -H "Authorization: Bearer $github_token" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$comment\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
