name: Branch Name Check

on:
  create:
    branches:
      - "*"

jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Extract branch name
      id: branch_name
      run: |
        branch_name=${{ github.ref }}
        echo "::set-output name=branch_name::$branch_name"
        
    - name: Run branch name check
      run: |
        branch_name="${{ steps.branch_name.outputs.branch_name }}"
        
        # Remove any non-numeric characters from the branch name
        cleaned_name=$(echo "$branch_name" | tr -cd '[:digit:]')
        
        if [ ${#cleaned_name} -eq 4 ]; then
          echo "Branch name is valid."
        else
          echo "Branch name is not valid."
          
          # Get the branch creator's username using the GitHub API
          creator=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            | jq -r '.[0].user.login')
          
          # Send a comment to the branch creator
          comment="Hi @$creator, the branch name '$branch_name' is not valid. Please ensure the branch name consists of exactly four integers."
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$comment\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
            
          exit 1
        fi
