name: Branch Name Check

on:
  create:
    branches:
      - "*"

jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Extract branch name
      id: branch_name
      run: |
        branch_name=${{ github.ref }}
        echo "::set-output name=branch_name::$branch_name"
        
    - name: Run branch name check
      run: |
        branch_name="${{ steps.branch_name.outputs.branch_name }}"
        
        # Remove any non-numeric characters from the branch name
        cleaned_name=$(echo "$branch_name" | tr -cd '[:digit:]')
        
        if [ ${#cleaned_name} -eq 4 ]; then
          echo "Branch name is valid."
        else
          echo "Branch name is not valid."
          exit 1
        fi
