name: Check Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$branch_name" =~ ^[0-9]{4}$ ]]; then
            echo "Invalid branch name format. Branch names should consist of exactly four numbers."
            exit 1
          fi
