name: Branch Name Check

on:
  pull_request:
    types:
      - opened

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch Name
        id: branch_check
        run: |
          branch_name=$(git branch --show-current)
          regex='^[0-9]{4}$'

          if [[ ! $branch_name =~ $regex ]]; then
            echo "Branch name '$branch_name' is invalid. It should consist of 4 digits."
            exit 1
          fi

      - name: Set Status Check
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-check@v1
        with:
          name: Branch Name Check
          conclusion: failure
          details_url: ${{ github.event.pull_request.html_url }}
          title: Invalid Branch Name
          summary: The branch name should consist of 4 digits.

      - name: Set Status Check
        if: ${{ success() }}
        uses: peter-evans/create-or-update-check@v1
        with:
          name: Branch Name Check
          conclusion: success
          details_url: ${{ github.event.pull_request.html_url }}
          title: Valid Branch Name
          summary: The branch name consists of 4 digits.
