name: Branch Name Check

on:
  push:
    branches-ignore:
      - '*'


jobs:
  branch_name_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Get last created branch name
        id: branch_name
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
      
      - name: Validate branch name
        run: |
          branch_name="${{ steps.branch_name.outputs.branch }}"
          if [[ "$branch" =~ ^sprint/[0-9]+.*$ || \
                  "$branch" =~ ^feature/D7-[0-9]+.*$ || \
                  "$branch" =~ ^fix/D7-[0-9]+.*$ || \
                  "$branch" =~ ^release/[0-9]+\.[0-9]+.*$ ]]; then
            echo "Branch name is valid"
          else
            echo "Branch name is invalid"
            exit 1
          fi
          
    
