name: Branch Name Check

on:
  pull_request:
    types:
      - opened

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch Name
        run: |
          branch_name=$(git branch --show-current)
          regex='^fix\/D7-[0-9]{4}$'

          if [[ ! $branch_name =~ $regex ]]; then
            echo "Branch name '$branch_name' is invalid. It should be in the format 'fix/D7-XXXX' where the last four X are integers."
            exit 1
          else
            echo "Branch name '$branch_name' is valid."
          fi
