name: Branch Name Validation

on:
  push:
    branches:
      - '*'
  create:
    branches:
      - '*'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch list
        id: get_branches
        run: echo "::set-output name=branches::$(git branch -r --format='%(refname:lstrip=2)')"

      - name: Iterate through branches
        id: iterate_branches
        run: |
          branches="${{ steps.get_branches.outputs.branches }}"
          for branch in $branches; do
            branch_name="${branch#origin/}"
            if [[ ! $branch_name =~ ^[0-9]{4}$ ]]; then
              echo "Invalid branch name: $branch_name"
              exit 1
            else
              echo "Valid branch name: $branch_name"
            fi
          done

      - name: Send error email notification
        if: ${{ job.status != 'success' }}
        run: |
          # Add code to send error email notification here
          echo "Branch name is not valid. Please ensure it consists of four integers."
